# Copyright 2026 Cloudfra
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG WINDOWS_VERSION=1809

FROM mcr.microsoft.com/windows/nanoserver:${WINDOWS_VERSION}

ARG BUILD_DATE
ARG VCS_REF
ARG BUILD_VERSION
ARG BINARY_NAME
ARG BINARY_PATH

COPY ${BINARY_PATH} /app/example.exe
COPY LICENSE /app/LICENSE

# hadolint ignore=DL3066
USER ContainerUser
EXPOSE 80
ENTRYPOINT ["/app/example.exe"]

# Standardized Docker Image Labels
# https://github.com/opencontainers/image-spec/blob/master/annotations.md
LABEL \
    org.opencontainers.image.created="${BUILD_DATE}" \
    org.opencontainers.image.authors="Cloudfra <cloudfra@googlegroups.com>" \
    org.opencontainers.image.url="https://github.com/cloudfra/example" \
    org.opencontainers.image.documentation="https://github.com/cloudfra/template-go" \
    org.opencontainers.image.source="https://github.com/cloudfra/template-go" \
    org.opencontainers.image.version="${BUILD_VERSION}" \
    org.opencontainers.image.revision="${VCS_REF}" \
    org.opencontainers.image.vendor="Cloudfra" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.ref.name="" \
    org.opencontainers.image.title="${BINARY_NAME}" \
    org.opencontainers.image.description="Example application." \
    org.label-schema.schema-version="1.0" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.url="https://github.com/cloudfra/template-go" \
    org.label-schema.vcs-url="https://github.com/cloudfra/template-go" \
    org.label-schema.version=$BUILD_VERSION \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vendor="Cloudfra" \
    org.label-schema.name="${BINARY_NAME}" \
    org.label-schema.description="Example application." \
    org.label-schema.usage="https://github.com/cloudfra/template-go"
